# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Список новостей'},
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor.fields.RichTextField(verbose_name='Короткий текст'),
        ),
    ]
