# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170620_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий текст'),
        ),
    ]
