# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170620_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Список новостей'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field=615, null=True, upload_to='', verbose_name='Изображение', width_field=973),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
