# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170620_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='news',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение будет автоматически приведено к размеру 973px * 615px', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
