# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170620_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальный размер для изображения - 973px * 615px', null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
