# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_is_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение'),
        ),
    ]
