# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Фото клиента'),
        ),
    ]
