# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20170621_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Промодерировано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
