# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20170627_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Список отзывов'},
        ),
    ]
