# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткое описание')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('prices', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Цены')),
                ('image', models.ImageField(blank=True, help_text='Оптимальный размер для изображения - 973px * 615px', null=True, upload_to='hostels/', verbose_name='Изображение')),
                ('address_google', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес для карты Google')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(max_length=255, verbose_name='Адрес, телефоны')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Хостел',
                'verbose_name_plural': 'Список хостелов',
            },
        ),
    ]
