# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальный размер для изображения - 339px * 216px', null=True, upload_to='hostels/', verbose_name='Изображение'),
        ),
    ]
