# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_auto_20170622_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.IntegerField(max_length=255, verbose_name='Значение, грн')),
            ],
            options={
                'verbose_name_plural': 'Цены',
                'verbose_name': 'Цена',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Список сервисов'},
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='prices',
        ),
        migrations.AddField(
            model_name='price',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.Hostel'),
        ),
    ]
