# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_auto_20170623_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.IntegerField(verbose_name='Значение, грн'),
        ),
    ]
