# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_auto_20170623_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='address_google',
        ),
        migrations.AddField(
            model_name='hostel',
            name='code_google_maps',
            field=models.TextField(blank=True, null=True, verbose_name='HTML-код карты Google'),
        ),
    ]
