# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='services',
            field=models.ManyToManyField(blank=True, to='hostels.Service'),
        ),
    ]
