# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Изображение')),
                ('head_text', models.CharField(max_length=255, verbose_name='Заглавный текст')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
