# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170620_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='short_description',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=123, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
