# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170620_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткое описание')),
                ('telephones', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Телефоны')),
            ],
            options={
                'verbose_name': 'Подвал (footer)',
                'verbose_name_plural': 'Подвал (footer)',
            },
        ),
    ]
