# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код HTML')),
            ],
            options={
                'verbose_name': 'Google Analytics (HTML код)',
                'verbose_name_plural': 'Google Analytics (HTML код)',
            },
        ),
    ]
